import { Nationality } from '../models/Nationality';

export const COUNTRIES: Nationality[] = [
  { code: 'AF', label: 'Afghan',                flag: '🇦🇫' },
  { code: 'AL', label: 'Albanian',              flag: '🇦🇱' },
  { code: 'DZ', label: 'Algerian',              flag: '🇩🇿' },
  { code: 'AD', label: 'Andorran',              flag: '🇦🇩' },
  { code: 'AO', label: 'Angolan',               flag: '🇦🇴' },
  { code: 'AG', label: 'Antiguan',              flag: '🇦🇬' },
  { code: 'AR', label: 'Argentine',             flag: '🇦🇷' },
  { code: 'AM', label: 'Armenian',              flag: '🇦🇲' },
  { code: 'AU', label: 'Australian',            flag: '🇦🇺' },
  { code: 'AT', label: 'Austrian',              flag: '🇦🇹' },
  { code: 'AZ', label: 'Azerbaijani',           flag: '🇦🇿' },
  { code: 'BS', label: 'Bahamian',              flag: '🇧🇸' },
  { code: 'BH', label: 'Bahraini',              flag: '🇧🇭' },
  { code: 'BD', label: 'Bangladeshi',           flag: '🇧🇩' },
  { code: 'BB', label: 'Barbadian',             flag: '🇧🇧' },
  { code: 'BY', label: 'Belarusian',            flag: '🇧🇾' },
  { code: 'BE', label: 'Belgian',               flag: '🇧🇪' },
  { code: 'BZ', label: 'Belizean',              flag: '🇧🇿' },
  { code: 'BJ', label: 'Beninese',              flag: '🇧🇯' },
  { code: 'BT', label: 'Bhutanese',             flag: '🇧🇹' },
  { code: 'BO', label: 'Bolivian',              flag: '🇧🇴' },
  { code: 'BA', label: 'Bosnian',               flag: '🇧🇦' },
  { code: 'BW', label: 'Botswanan',             flag: '🇧🇼' },
  { code: 'BR', label: 'Brazilian',             flag: '🇧🇷' },
  { code: 'BN', label: 'Bruneian',              flag: '🇧🇳' },
  { code: 'BG', label: 'Bulgarian',             flag: '🇧🇬' },
  { code: 'BF', label: 'Burkinabé',             flag: '🇧🇫' },
  { code: 'BI', label: 'Burundian',             flag: '🇧🇮' },
  { code: 'CV', label: 'Cape Verdean',          flag: '🇨🇻' },
  { code: 'KH', label: 'Cambodian',             flag: '🇰🇭' },
  { code: 'CM', label: 'Cameroonian',           flag: '🇨🇲' },
  { code: 'CA', label: 'Canadian',              flag: '🇨🇦' },
  { code: 'CF', label: 'Central African',       flag: '🇨🇫' },
  { code: 'TD', label: 'Chadian',               flag: '🇹🇩' },
  { code: 'CL', label: 'Chilean',               flag: '🇨🇱' },
  { code: 'CN', label: 'Chinese',               flag: '🇨🇳' },
  { code: 'CO', label: 'Colombian',             flag: '🇨🇴' },
  { code: 'KM', label: 'Comorian',              flag: '🇰🇲' },
  { code: 'CG', label: 'Congolese',             flag: '🇨🇬' },
  { code: 'CR', label: 'Costa Rican',           flag: '🇨🇷' },
  { code: 'HR', label: 'Croatian',              flag: '🇭🇷' },
  { code: 'CU', label: 'Cuban',                 flag: '🇨🇺' },
  { code: 'CY', label: 'Cypriot',               flag: '🇨🇾' },
  { code: 'CZ', label: 'Czech',                 flag: '🇨🇿' },
  { code: 'DK', label: 'Danish',                flag: '🇩🇰' },
  { code: 'DJ', label: 'Djiboutian',            flag: '🇩🇯' },
  { code: 'DM', label: 'Dominican',             flag: '🇩🇲' },
  { code: 'DO', label: 'Dominican Republic',    flag: '🇩🇴' },
  { code: 'EC', label: 'Ecuadorian',            flag: '🇪🇨' },
  { code: 'EG', label: 'Egyptian',              flag: '🇪🇬' },
  { code: 'SV', label: 'Salvadoran',            flag: '🇸🇻' },
  { code: 'GQ', label: 'Equatoguinean',         flag: '🇬🇶' },
  { code: 'ER', label: 'Eritrean',              flag: '🇪🇷' },
  { code: 'EE', label: 'Estonian',              flag: '🇪🇪' },
  { code: 'SZ', label: 'Swazi',                 flag: '🇸🇿' },
  { code: 'ET', label: 'Ethiopian',             flag: '🇪🇹' },
  { code: 'FJ', label: 'Fijian',                flag: '🇫🇯' },
  { code: 'FI', label: 'Finnish',               flag: '🇫🇮' },
  { code: 'FR', label: 'French',                flag: '🇫🇷' },
  { code: 'GA', label: 'Gabonese',              flag: '🇬🇦' },
  { code: 'GM', label: 'Gambian',               flag: '🇬🇲' },
  { code: 'GE', label: 'Georgian',              flag: '🇬🇪' },
  { code: 'DE', label: 'German',                flag: '🇩🇪' },
  { code: 'GH', label: 'Ghanaian',              flag: '🇬🇭' },
  { code: 'GR', label: 'Greek',                 flag: '🇬🇷' },
  { code: 'GD', label: 'Grenadian',             flag: '🇬🇩' },
  { code: 'GT', label: 'Guatemalan',            flag: '🇬🇹' },
  { code: 'GN', label: 'Guinean',               flag: '🇬🇳' },
  { code: 'GW', label: 'Bissau-Guinean',        flag: '🇬🇼' },
  { code: 'GY', label: 'Guyanese',              flag: '🇬🇾' },
  { code: 'HT', label: 'Haitian',               flag: '🇭🇹' },
  { code: 'HN', label: 'Honduran',              flag: '🇭🇳' },
  { code: 'HU', label: 'Hungarian',             flag: '🇭🇺' },
  { code: 'IS', label: 'Icelandic',             flag: '🇮🇸' },
  { code: 'IN', label: 'Indian',                flag: '🇮🇳' },
  { code: 'ID', label: 'Indonesian',            flag: '🇮🇩' },
  { code: 'IR', label: 'Iranian',               flag: '🇮🇷' },
  { code: 'IQ', label: 'Iraqi',                 flag: '🇮🇶' },
  { code: 'IE', label: 'Irish',                 flag: '🇮🇪' },
  { code: 'IL', label: 'Israeli',               flag: '🇮🇱' },
  { code: 'IT', label: 'Italian',               flag: '🇮🇹' },
  { code: 'JM', label: 'Jamaican',              flag: '🇯🇲' },
  { code: 'JP', label: 'Japanese',              flag: '🇯🇵' },
  { code: 'JO', label: 'Jordanian',             flag: '🇯🇴' },
  { code: 'KZ', label: 'Kazakhstani',           flag: '🇰🇿' },
  { code: 'KE', label: 'Kenyan',                flag: '🇰🇪' },
  { code: 'KI', label: 'I-Kiribati',            flag: '🇰🇮' },
  { code: 'KW', label: 'Kuwaiti',               flag: '🇰🇼' },
  { code: 'KG', label: 'Kyrgyz',                flag: '🇰🇬' },
  { code: 'LA', label: 'Laotian',               flag: '🇱🇦' },
  { code: 'LV', label: 'Latvian',               flag: '🇱🇻' },
  { code: 'LB', label: 'Lebanese',              flag: '🇱🇧' },
  { code: 'LS', label: 'Basotho',               flag: '🇱🇸' },
  { code: 'LR', label: 'Liberian',              flag: '🇱🇷' },
  { code: 'LY', label: 'Libyan',                flag: '🇱🇾' },
  { code: 'LI', label: 'Liechtensteiner',       flag: '🇱🇮' },
  { code: 'LT', label: 'Lithuanian',            flag: '🇱🇹' },
  { code: 'LU', label: 'Luxembourgish',         flag: '🇱🇺' },
  { code: 'MG', label: 'Malagasy',              flag: '🇲🇬' },
  { code: 'MW', label: 'Malawian',              flag: '🇲🇼' },
  { code: 'MY', label: 'Malaysian',             flag: '🇲🇾' },
  { code: 'MV', label: 'Maldivian',             flag: '🇲🇻' },
  { code: 'ML', label: 'Malian',                flag: '🇲🇱' },
  { code: 'MT', label: 'Maltese',               flag: '🇲🇹' },
  { code: 'MH', label: 'Marshallese',           flag: '🇲🇭' },
  { code: 'MR', label: 'Mauritanian',           flag: '🇲🇷' },
  { code: 'MU', label: 'Mauritian',             flag: '🇲🇺' },
  { code: 'MX', label: 'Mexican',               flag: '🇲🇽' },
  { code: 'FM', label: 'Micronesian',           flag: '🇫🇲' },
  { code: 'MD', label: 'Moldovan',              flag: '🇲🇩' },
  { code: 'MC', label: 'Monégasque',            flag: '🇲🇨' },
  { code: 'MN', label: 'Mongolian',             flag: '🇲🇳' },
  { code: 'ME', label: 'Montenegrin',           flag: '🇲🇪' },
  { code: 'MA', label: 'Moroccan',              flag: '🇲🇦' },
  { code: 'MZ', label: 'Mozambican',            flag: '🇲🇿' },
  { code: 'MM', label: 'Burmese',               flag: '🇲🇲' },
  { code: 'NA', label: 'Namibian',              flag: '🇳🇦' },
  { code: 'NR', label: 'Nauruan',               flag: '🇳🇷' },
  { code: 'NP', label: 'Nepali',                flag: '🇳🇵' },
  { code: 'NL', label: 'Dutch',                 flag: '🇳🇱' },
  { code: 'NZ', label: 'New Zealander',         flag: '🇳🇿' },
  { code: 'NI', label: 'Nicaraguan',            flag: '🇳🇮' },
  { code: 'NE', label: 'Nigerien',              flag: '🇳🇪' },
  { code: 'NG', label: 'Nigerian',              flag: '🇳🇬' },
  { code: 'MK', label: 'North Macedonian',      flag: '🇲🇰' },
  { code: 'NO', label: 'Norwegian',             flag: '🇳🇴' },
  { code: 'OM', label: 'Omani',                 flag: '🇴🇲' },
  { code: 'PK', label: 'Pakistani',             flag: '🇵🇰' },
  { code: 'PW', label: 'Palauan',               flag: '🇵🇼' },
  { code: 'PS', label: 'Palestinian',           flag: '🇵🇸' },
  { code: 'PA', label: 'Panamanian',            flag: '🇵🇦' },
  { code: 'PG', label: 'Papua New Guinean',     flag: '🇵🇬' },
  { code: 'PY', label: 'Paraguayan',            flag: '🇵🇾' },
  { code: 'PE', label: 'Peruvian',              flag: '🇵🇪' },
  { code: 'PH', label: 'Filipino',              flag: '🇵🇭' },
  { code: 'PL', label: 'Polish',                flag: '🇵🇱' },
  { code: 'PT', label: 'Portuguese',            flag: '🇵🇹' },
  { code: 'QA', label: 'Qatari',                flag: '🇶🇦' },
  { code: 'RO', label: 'Romanian',              flag: '🇷🇴' },
  { code: 'RU', label: 'Russian',               flag: '🇷🇺' },
  { code: 'RW', label: 'Rwandan',               flag: '🇷🇼' },
  { code: 'KN', label: 'Kittitian',             flag: '🇰🇳' },
  { code: 'LC', label: 'Saint Lucian',          flag: '🇱🇨' },
  { code: 'VC', label: 'Vincentian',            flag: '🇻🇨' },
  { code: 'WS', label: 'Samoan',                flag: '🇼🇸' },
  { code: 'SM', label: 'Sammarinese',           flag: '🇸🇲' },
  { code: 'ST', label: 'São Toméan',            flag: '🇸🇹' },
  { code: 'SA', label: 'Saudi',                 flag: '🇸🇦' },
  { code: 'SN', label: 'Senegalese',            flag: '🇸🇳' },
  { code: 'RS', label: 'Serbian',               flag: '🇷🇸' },
  { code: 'SC', label: 'Seychellois',           flag: '🇸🇨' },
  { code: 'SL', label: 'Sierra Leonean',        flag: '🇸🇱' },
  { code: 'SG', label: 'Singaporean',           flag: '🇸🇬' },
  { code: 'SK', label: 'Slovak',                flag: '🇸🇰' },
  { code: 'SI', label: 'Slovenian',             flag: '🇸🇮' },
  { code: 'SB', label: 'Solomon Islander',      flag: '🇸🇧' },
  { code: 'SO', label: 'Somali',                flag: '🇸🇴' },
  { code: 'ZA', label: 'South African',         flag: '🇿🇦' },
  { code: 'SS', label: 'South Sudanese',        flag: '🇸🇸' },
  { code: 'KR', label: 'South Korean',          flag: '🇰🇷' },
  { code: 'ES', label: 'Spanish',               flag: '🇪🇸' },
  { code: 'LK', label: 'Sri Lankan',            flag: '🇱🇰' },
  { code: 'SD', label: 'Sudanese',              flag: '🇸🇩' },
  { code: 'SR', label: 'Surinamese',            flag: '🇸🇷' },
  { code: 'SE', label: 'Swedish',               flag: '🇸🇪' },
  { code: 'CH', label: 'Swiss',                 flag: '🇨🇭' },
  { code: 'SY', label: 'Syrian',                flag: '🇸🇾' },
  { code: 'TW', label: 'Taiwanese',             flag: '🇹🇼' },
  { code: 'TJ', label: 'Tajik',                 flag: '🇹🇯' },
  { code: 'TZ', label: 'Tanzanian',             flag: '🇹🇿' },
  { code: 'TH', label: 'Thai',                  flag: '🇹🇭' },
  { code: 'TL', label: 'Timorese',              flag: '🇹🇱' },
  { code: 'TG', label: 'Togolese',              flag: '🇹🇬' },
  { code: 'TO', label: 'Tongan',                flag: '🇹🇴' },
  { code: 'TT', label: 'Trinidadian',           flag: '🇹🇹' },
  { code: 'TN', label: 'Tunisian',              flag: '🇹🇳' },
  { code: 'TR', label: 'Turkish',               flag: '🇹🇷' },
  { code: 'TM', label: 'Turkmen',               flag: '🇹🇲' },
  { code: 'TV', label: 'Tuvaluan',              flag: '🇹🇻' },
  { code: 'UG', label: 'Ugandan',               flag: '🇺🇬' },
  { code: 'UA', label: 'Ukrainian',             flag: '🇺🇦' },
  { code: 'AE', label: 'Emirati',               flag: '🇦🇪' },
  { code: 'GB', label: 'British',               flag: '🇬🇧' },
  { code: 'US', label: 'American',              flag: '🇺🇸' },
  { code: 'UY', label: 'Uruguayan',             flag: '🇺🇾' },
  { code: 'UZ', label: 'Uzbek',                 flag: '🇺🇿' },
  { code: 'VU', label: 'Ni-Vanuatu',            flag: '🇻🇺' },
  { code: 'VA', label: 'Vatican',               flag: '🇻🇦' },
  { code: 'VE', label: 'Venezuelan',            flag: '🇻🇪' },
  { code: 'VN', label: 'Vietnamese',            flag: '🇻🇳' },
  { code: 'YE', label: 'Yemeni',                flag: '🇾🇪' },
  { code: 'ZM', label: 'Zambian',               flag: '🇿🇲' },
  { code: 'ZW', label: 'Zimbabwean',            flag: '🇿🇼' },
];
