import { Nationality } from '../models/Nationality';

export const COUNTRIES: Nationality[] = [
  { code: 'AF', label: 'Afghan',             flagClass: 'flag:AF' },
  { code: 'AL', label: 'Albanian',           flagClass: 'flag:AL' },
  { code: 'DZ', label: 'Algerian',           flagClass: 'flag:DZ' },
  { code: 'AD', label: 'Andorran',           flagClass: 'flag:AD' },
  { code: 'AO', label: 'Angolan',            flagClass: 'flag:AO' },
  { code: 'AG', label: 'Antiguan',           flagClass: 'flag:AG' },
  { code: 'AR', label: 'Argentine',          flagClass: 'flag:AR' },
  { code: 'AM', label: 'Armenian',           flagClass: 'flag:AM' },
  { code: 'AU', label: 'Australian',         flagClass: 'flag:AU' },
  { code: 'AT', label: 'Austrian',           flagClass: 'flag:AT' },
  { code: 'AZ', label: 'Azerbaijani',        flagClass: 'flag:AZ' },
  { code: 'BS', label: 'Bahamian',           flagClass: 'flag:BS' },
  { code: 'BH', label: 'Bahraini',           flagClass: 'flag:BH' },
  { code: 'BD', label: 'Bangladeshi',        flagClass: 'flag:BD' },
  { code: 'BB', label: 'Barbadian',          flagClass: 'flag:BB' },
  { code: 'BY', label: 'Belarusian',         flagClass: 'flag:BY' },
  { code: 'BE', label: 'Belgian',            flagClass: 'flag:BE' },
  { code: 'BZ', label: 'Belizean',           flagClass: 'flag:BZ' },
  { code: 'BJ', label: 'Beninese',           flagClass: 'flag:BJ' },
  { code: 'BT', label: 'Bhutanese',          flagClass: 'flag:BT' },
  { code: 'BO', label: 'Bolivian',           flagClass: 'flag:BO' },
  { code: 'BA', label: 'Bosnian',            flagClass: 'flag:BA' },
  { code: 'BW', label: 'Botswanan',          flagClass: 'flag:BW' },
  { code: 'BR', label: 'Brazilian',          flagClass: 'flag:BR' },
  { code: 'BN', label: 'Bruneian',           flagClass: 'flag:BN' },
  { code: 'BG', label: 'Bulgarian',          flagClass: 'flag:BG' },
  { code: 'BF', label: 'Burkinabé',          flagClass: 'flag:BF' },
  { code: 'BI', label: 'Burundian',          flagClass: 'flag:BI' },
  { code: 'CV', label: 'Cape Verdean',       flagClass: 'flag:CV' },
  { code: 'KH', label: 'Cambodian',          flagClass: 'flag:KH' },
  { code: 'CM', label: 'Cameroonian',        flagClass: 'flag:CM' },
  { code: 'CA', label: 'Canadian',           flagClass: 'flag:CA' },
  { code: 'CF', label: 'Central African',    flagClass: 'flag:CF' },
  { code: 'TD', label: 'Chadian',            flagClass: 'flag:TD' },
  { code: 'CL', label: 'Chilean',            flagClass: 'flag:CL' },
  { code: 'CN', label: 'Chinese',            flagClass: 'flag:CN' },
  { code: 'CO', label: 'Colombian',          flagClass: 'flag:CO' },
  { code: 'KM', label: 'Comorian',           flagClass: 'flag:KM' },
  { code: 'CG', label: 'Congolese',          flagClass: 'flag:CG' },
  { code: 'CR', label: 'Costa Rican',        flagClass: 'flag:CR' },
  { code: 'HR', label: 'Croatian',           flagClass: 'flag:HR' },
  { code: 'CU', label: 'Cuban',              flagClass: 'flag:CU' },
  { code: 'CY', label: 'Cypriot',            flagClass: 'flag:CY' },
  { code: 'CZ', label: 'Czech',              flagClass: 'flag:CZ' },
  { code: 'DK', label: 'Danish',             flagClass: 'flag:DK' },
  { code: 'DJ', label: 'Djiboutian',         flagClass: 'flag:DJ' },
  { code: 'DM', label: 'Dominican',          flagClass: 'flag:DM' },
  { code: 'DO', label: 'Dominican Republic', flagClass: 'flag:DO' },
  { code: 'EC', label: 'Ecuadorian',         flagClass: 'flag:EC' },
  { code: 'EG', label: 'Egyptian',           flagClass: 'flag:EG' },
  { code: 'SV', label: 'Salvadoran',         flagClass: 'flag:SV' },
  { code: 'GQ', label: 'Equatoguinean',      flagClass: 'flag:GQ' },
  { code: 'ER', label: 'Eritrean',           flagClass: 'flag:ER' },
  { code: 'EE', label: 'Estonian',           flagClass: 'flag:EE' },
  { code: 'SZ', label: 'Swazi',              flagClass: 'flag:SZ' },
  { code: 'ET', label: 'Ethiopian',          flagClass: 'flag:ET' },
  { code: 'FJ', label: 'Fijian',             flagClass: 'flag:FJ' },
  { code: 'FI', label: 'Finnish',            flagClass: 'flag:FI' },
  { code: 'FR', label: 'French',             flagClass: 'flag:FR' },
  { code: 'GA', label: 'Gabonese',           flagClass: 'flag:GA' },
  { code: 'GM', label: 'Gambian',            flagClass: 'flag:GM' },
  { code: 'GE', label: 'Georgian',           flagClass: 'flag:GE' },
  { code: 'DE', label: 'German',             flagClass: 'flag:DE' },
  { code: 'GH', label: 'Ghanaian',           flagClass: 'flag:GH' },
  { code: 'GR', label: 'Greek',              flagClass: 'flag:GR' },
  { code: 'GD', label: 'Grenadian',          flagClass: 'flag:GD' },
  { code: 'GT', label: 'Guatemalan',         flagClass: 'flag:GT' },
  { code: 'GN', label: 'Guinean',            flagClass: 'flag:GN' },
  { code: 'GW', label: 'Bissau-Guinean',     flagClass: 'flag:GW' },
  { code: 'GY', label: 'Guyanese',           flagClass: 'flag:GY' },
  { code: 'HT', label: 'Haitian',            flagClass: 'flag:HT' },
  { code: 'HN', label: 'Honduran',           flagClass: 'flag:HN' },
  { code: 'HU', label: 'Hungarian',          flagClass: 'flag:HU' },
  { code: 'IS', label: 'Icelandic',          flagClass: 'flag:IS' },
  { code: 'IN', label: 'Indian',             flagClass: 'flag:IN' },
  { code: 'ID', label: 'Indonesian',         flagClass: 'flag:ID' },
  { code: 'IR', label: 'Iranian',            flagClass: 'flag:IR' },
  { code: 'IQ', label: 'Iraqi',              flagClass: 'flag:IQ' },
  { code: 'IE', label: 'Irish',              flagClass: 'flag:IE' },
  { code: 'IL', label: 'Israeli',            flagClass: 'flag:IL' },
  { code: 'IT', label: 'Italian',            flagClass: 'flag:IT' },
  { code: 'JM', label: 'Jamaican',           flagClass: 'flag:JM' },
  { code: 'JP', label: 'Japanese',           flagClass: 'flag:JP' },
  { code: 'JO', label: 'Jordanian',          flagClass: 'flag:JO' },
  { code: 'KZ', label: 'Kazakhstani',        flagClass: 'flag:KZ' },
  { code: 'KE', label: 'Kenyan',             flagClass: 'flag:KE' },
  { code: 'KI', label: 'I-Kiribati',         flagClass: 'flag:KI' },
  { code: 'KW', label: 'Kuwaiti',            flagClass: 'flag:KW' },
  { code: 'KG', label: 'Kyrgyz',             flagClass: 'flag:KG' },
  { code: 'LA', label: 'Laotian',            flagClass: 'flag:LA' },
  { code: 'LV', label: 'Latvian',            flagClass: 'flag:LV' },
  { code: 'LB', label: 'Lebanese',           flagClass: 'flag:LB' },
  { code: 'LS', label: 'Basotho',            flagClass: 'flag:LS' },
  { code: 'LR', label: 'Liberian',           flagClass: 'flag:LR' },
  { code: 'LY', label: 'Libyan',             flagClass: 'flag:LY' },
  { code: 'LI', label: 'Liechtensteiner',    flagClass: 'flag:LI' },
  { code: 'LT', label: 'Lithuanian',         flagClass: 'flag:LT' },
  { code: 'LU', label: 'Luxembourgish',      flagClass: 'flag:LU' },
  { code: 'MG', label: 'Malagasy',           flagClass: 'flag:MG' },
  { code: 'MW', label: 'Malawian',           flagClass: 'flag:MW' },
  { code: 'MY', label: 'Malaysian',          flagClass: 'flag:MY' },
  { code: 'MV', label: 'Maldivian',          flagClass: 'flag:MV' },
  { code: 'ML', label: 'Malian',             flagClass: 'flag:ML' },
  { code: 'MT', label: 'Maltese',            flagClass: 'flag:MT' },
  { code: 'MH', label: 'Marshallese',        flagClass: 'flag:MH' },
  { code: 'MR', label: 'Mauritanian',        flagClass: 'flag:MR' },
  { code: 'MU', label: 'Mauritian',          flagClass: 'flag:MU' },
  { code: 'MX', label: 'Mexican',            flagClass: 'flag:MX' },
  { code: 'FM', label: 'Micronesian',        flagClass: 'flag:FM' },
  { code: 'MD', label: 'Moldovan',           flagClass: 'flag:MD' },
  { code: 'MC', label: 'Monégasque',         flagClass: 'flag:MC' },
  { code: 'MN', label: 'Mongolian',          flagClass: 'flag:MN' },
  { code: 'ME', label: 'Montenegrin',        flagClass: 'flag:ME' },
  { code: 'MA', label: 'Moroccan',           flagClass: 'flag:MA' },
  { code: 'MZ', label: 'Mozambican',         flagClass: 'flag:MZ' },
  { code: 'MM', label: 'Burmese',            flagClass: 'flag:MM' },
  { code: 'NA', label: 'Namibian',           flagClass: 'flag:NA' },
  { code: 'NR', label: 'Nauruan',            flagClass: 'flag:NR' },
  { code: 'NP', label: 'Nepali',             flagClass: 'flag:NP' },
  { code: 'NL', label: 'Dutch',              flagClass: 'flag:NL' },
  { code: 'NZ', label: 'New Zealander',      flagClass: 'flag:NZ' },
  { code: 'NI', label: 'Nicaraguan',         flagClass: 'flag:NI' },
  { code: 'NE', label: 'Nigerien',           flagClass: 'flag:NE' },
  { code: 'NG', label: 'Nigerian',           flagClass: 'flag:NG' },
  { code: 'MK', label: 'North Macedonian',   flagClass: 'flag:MK' },
  { code: 'NO', label: 'Norwegian',          flagClass: 'flag:NO' },
  { code: 'OM', label: 'Omani',              flagClass: 'flag:OM' },
  { code: 'PK', label: 'Pakistani',          flagClass: 'flag:PK' },
  { code: 'PW', label: 'Palauan',            flagClass: 'flag:PW' },
  { code: 'PS', label: 'Palestinian',        flagClass: 'flag:PS' },
  { code: 'PA', label: 'Panamanian',         flagClass: 'flag:PA' },
  { code: 'PG', label: 'Papua New Guinean',  flagClass: 'flag:PG' },
  { code: 'PY', label: 'Paraguayan',         flagClass: 'flag:PY' },
  { code: 'PE', label: 'Peruvian',           flagClass: 'flag:PE' },
  { code: 'PH', label: 'Filipino',           flagClass: 'flag:PH' },
  { code: 'PL', label: 'Polish',             flagClass: 'flag:PL' },
  { code: 'PT', label: 'Portuguese',         flagClass: 'flag:PT' },
  { code: 'QA', label: 'Qatari',             flagClass: 'flag:QA' },
  { code: 'RO', label: 'Romanian',           flagClass: 'flag:RO' },
  { code: 'RU', label: 'Russian',            flagClass: 'flag:RU' },
  { code: 'RW', label: 'Rwandan',            flagClass: 'flag:RW' },
  { code: 'KN', label: 'Kittitian',          flagClass: 'flag:KN' },
  { code: 'LC', label: 'Saint Lucian',       flagClass: 'flag:LC' },
  { code: 'VC', label: 'Vincentian',         flagClass: 'flag:VC' },
  { code: 'WS', label: 'Samoan',             flagClass: 'flag:WS' },
  { code: 'SM', label: 'Sammarinese',        flagClass: 'flag:SM' },
  { code: 'ST', label: 'São Toméan',         flagClass: 'flag:ST' },
  { code: 'SA', label: 'Saudi',              flagClass: 'flag:SA' },
  { code: 'SN', label: 'Senegalese',         flagClass: 'flag:SN' },
  { code: 'RS', label: 'Serbian',            flagClass: 'flag:RS' },
  { code: 'SC', label: 'Seychellois',        flagClass: 'flag:SC' },
  { code: 'SL', label: 'Sierra Leonean',     flagClass: 'flag:SL' },
  { code: 'SG', label: 'Singaporean',        flagClass: 'flag:SG' },
  { code: 'SK', label: 'Slovak',             flagClass: 'flag:SK' },
  { code: 'SI', label: 'Slovenian',          flagClass: 'flag:SI' },
  { code: 'SB', label: 'Solomon Islander',   flagClass: 'flag:SB' },
  { code: 'SO', label: 'Somali',             flagClass: 'flag:SO' },
  { code: 'ZA', label: 'South African',      flagClass: 'flag:ZA' },
  { code: 'SS', label: 'South Sudanese',     flagClass: 'flag:SS' },
  { code: 'KR', label: 'South Korean',       flagClass: 'flag:KR' },
  { code: 'ES', label: 'Spanish',            flagClass: 'flag:ES' },
  { code: 'LK', label: 'Sri Lankan',         flagClass: 'flag:LK' },
  { code: 'SD', label: 'Sudanese',           flagClass: 'flag:SD' },
  { code: 'SR', label: 'Surinamese',         flagClass: 'flag:SR' },
  { code: 'SE', label: 'Swedish',            flagClass: 'flag:SE' },
  { code: 'CH', label: 'Swiss',              flagClass: 'flag:CH' },
  { code: 'SY', label: 'Syrian',             flagClass: 'flag:SY' },
  { code: 'TW', label: 'Taiwanese',          flagClass: 'flag:TW' },
  { code: 'TJ', label: 'Tajik',              flagClass: 'flag:TJ' },
  { code: 'TZ', label: 'Tanzanian',          flagClass: 'flag:TZ' },
  { code: 'TH', label: 'Thai',               flagClass: 'flag:TH' },
  { code: 'TL', label: 'Timorese',           flagClass: 'flag:TL' },
  { code: 'TG', label: 'Togolese',           flagClass: 'flag:TG' },
  { code: 'TO', label: 'Tongan',             flagClass: 'flag:TO' },
  { code: 'TT', label: 'Trinidadian',        flagClass: 'flag:TT' },
  { code: 'TN', label: 'Tunisian',           flagClass: 'flag:TN' },
  { code: 'TR', label: 'Turkish',            flagClass: 'flag:TR' },
  { code: 'TM', label: 'Turkmen',            flagClass: 'flag:TM' },
  { code: 'TV', label: 'Tuvaluan',           flagClass: 'flag:TV' },
  { code: 'UG', label: 'Ugandan',            flagClass: 'flag:UG' },
  { code: 'UA', label: 'Ukrainian',          flagClass: 'flag:UA' },
  { code: 'AE', label: 'Emirati',            flagClass: 'flag:AE' },
  { code: 'GB', label: 'British',            flagClass: 'flag:GB' },
  { code: 'US', label: 'American',           flagClass: 'flag:US' },
  { code: 'UY', label: 'Uruguayan',          flagClass: 'flag:UY' },
  { code: 'UZ', label: 'Uzbek',              flagClass: 'flag:UZ' },
  { code: 'VU', label: 'Ni-Vanuatu',         flagClass: 'flag:VU' },
  { code: 'VA', label: 'Vatican',            flagClass: 'flag:VA' },
  { code: 'VE', label: 'Venezuelan',         flagClass: 'flag:VE' },
  { code: 'VN', label: 'Vietnamese',         flagClass: 'flag:VN' },
  { code: 'YE', label: 'Yemeni',             flagClass: 'flag:YE' },
  { code: 'ZM', label: 'Zambian',            flagClass: 'flag:ZM' },
  { code: 'ZW', label: 'Zimbabwean',         flagClass: 'flag:ZW' },
];
