import { inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

import { Observable } from 'rxjs';

import { environment } from '../../environment';
import { Flashcard } from '../../models/flashcard.model';


@Injectable({
  providedIn: 'root'
})
export class FlashcardService {

  private readonly http = inject(HttpClient);

  private readonly apiUrl =
    `${environment.springApiUrl}/flashcards`;


  /**
   * Get flashcards generated by the AI.
   *
   * GET /api/flashcards/generated
   */
  getGeneratedFlashcards(): Observable<Flashcard[]> {

    return this.http.get<Flashcard[]>(
      `${this.apiUrl}/generated`
    );
  }


  /**
   * Get all saved flashcards.
   *
   * GET /api/flashcards
   */
  getAllFlashcards(): Observable<Flashcard[]> {

    return this.http.get<Flashcard[]>(
      this.apiUrl
    );
  }


  /**
   * Save the currently generated flashcards.
   *
   * POST /api/flashcards
   */
  saveGeneratedFlashcards(): Observable<string> {

    return this.http.post(
      this.apiUrl,
      {},
      {
        responseType: 'text'
      }
    );
  }


  /**
   * Get all flashcards belonging to a specific lesson.
   *
   * GET /api/flashcards/lesson/{lessonId}
   */
  getLessonFlashcards(
    lessonId: string
  ): Observable<Flashcard[]> {

    return this.http.get<Flashcard[]>(
      `${this.apiUrl}/lesson/${encodeURIComponent(lessonId)}`
    );
  }
}
