spring.application.name=blogproject

# ==========================================================
# SERVER
# ==========================================================

server.port=8083


# ==========================================================
# MONGODB
# ==========================================================

spring.mongodb.uri=mongodb://localhost:27020/blog_database


# ==========================================================
# MAIL
# ==========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.username=yassine.kerfai@etudiant-enit.utm.tn
spring.mail.password=nsah hsrl cazg fatj

email=noreply@blogproject.com

JWT_SECRET=KeyForJwtBlogPersonalKerfaiTwentysixgermany
JWT_EXPIRATION_MS=86400000


# ==========================================================
# KAFKA
# ==========================================================

bootstrap.server.config=localhost:9092


# ==========================================================
# KAFKA CONSUMER GROUPS
# ==========================================================

kafka.group.soundtrack=soundtrack-group
kafka.group.flashcard=flashcard-group
kafka.group.quiz=quiz-group
kafka.group.recommendation=recommendation-group
kafka.group.skill-keyword=skill-keyword-group


# ==========================================================
# KAFKA CONSUMER
# ==========================================================

kafka.consumer.auto-offset-reset=earliest
kafka.consumer.enable-auto-commit=true