spring.application.name=blogproject

# ==========================================================
# SERVER
# ==========================================================

server.port=8083


# ==========================================================
# MONGODB
# ==========================================================

spring.mongodb.uri=${MONGODB_URI}


# ==========================================================
# MAIL
# ==========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

email=${MAIL_FROM}


# ==========================================================
# KAFKA
# ==========================================================

bootstrap.server.config=${KAFKA_BOOTSTRAP_SERVERS}


# ==========================================================
# KAFKA CONSUMER GROUPS
# ==========================================================

kafka.group.soundtrack=soundtrack-group
kafka.group.flashcard=flashcard-group
kafka.group.quiz=quiz-group
kafka.group.recommendation=recommendation-group
kafka.group.skill-keyword=skill-keyword-group


# ==========================================================
# KAFKA CONSUMER
# ==========================================================

kafka.consumer.auto-offset-reset=earliest
kafka.consumer.enable-auto-commit=true